{
  "name": "await-catch",
  "version": "1.1.0",
  "description": "Async await wrapper for easy error handling",
  "main": "./src/index.js",
  "scripts": {
    "build": "NODE_ENV=\"production\" babel src -d lib",
    "prepublish": "npm tun build",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "async-await",
    "async",
    "catch",
    "try-catch",
    "try",
    "catch",
    "es6"
  ],
  "bugs": {
    "url": "https://github.com/bufface/await-catch/issues",
    "email": "bufface@gmail.com"
  },
  "homepage": "https://github.com/bufface/await-catch",
  "repository": {
    "type": "git",
    "url": "https://github.com/bufface/await-catch"
  },
  "author": "Cristian Buffa <bufface@gmail.com> (https://github.com/bufface)",
  "license": "MIT",
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-preset-babili": "^0.1.4",
    "babel-preset-env": "^1.6.1"
  }
}
